# -*- coding: utf-8 -*-
"""EX4_AppleStock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bHoKg3TG7xIVHGAtJn-KCcYzJq71kKaS
"""

#-------Manipulando dados com ações---------
import pandas as pd
dataset = pd.read_csv('Tesla.csv')
dataset['Date'] = pd.to_datetime(dataset['Date'])
dataset.head()
#-------Seleciona o maior valor de abertura da ação 'Open' e o menor valor de fechamento 'Close'---------
dataset['Open'].max()
dataset['Close'].min()
#-------Calcula a diferença entre o maior valor da coluna 'High' e o menor valor da coluna 'Low'---------
maValor = int(dataset['High'].max())
meValor = int(dataset['Low'].min())
total = int(maValor - meValor)
print (total)
#-------Seleciona a data maior valor da ação 'High' e a data do menor valor da ação 'Low'--------
print(dataset.ix[dataset['High'].idxmax()])
print(dataset.ix[dataset['Low'].idxmin()])
#-------Calcula a flutuação das ações em todo o dataset---------
i = int(0)
vetFlutuacao = []
for x in dataset['Date']:
  maValor = float(dataset['High'].iloc[i])
  meValor = float(dataset['Low'].iloc[i])
  total = (maValor - meValor)
  vetFlutuacao.append(total)
  i+=1
dataset['Flutuacao']=vetFlutuacao
#-------Constroi um gráfico da flutação da ação---------
for x in vetFlutuacao:
  print(x)
plt.plot_date(dataset['Date'], vetFlutuacao, color='r',fmt="r-")
#-------Seleciona todas as vezes que a flutuação da ação superou 5 dolares---------
maior_cinco = dataset[dataset['Flutuacao'] >= 5.0]
maior_cinco.head(30)
#-------Seleciona os campos 'Close' e 'Volume' e calcula a correlação entre eles---------
dataset[['Close','Volume']].corr()
dataset[dataset.corr(method ='pearson')>0.9] 
#-------Identifica quais campos possuem correlação maior que 90%---------
maior_noventa = dataset.corr() >= 0.9
maior_noventa.head(7)