# -*- coding: utf-8 -*-
"""Primeiros passos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-HRoQmIicltylOZlYBt8rA1rkfnrhKw
"""

"""
Exercicio 1 - Entrada de dados e atribuições

Faça um script que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê: salário bruto. quanto pagou ao INSS. quanto pagou ao sindicato. o salário líquido. calcule os descontos e o salário líquido, conforme a tabela abaixo:

Salário Bruto : RS
IR (11%) : RS
INSS (8%) : RS
Sindicato (5%) : RS = Salário Liquido : RS
Obs.: Salário Bruto - Descontos = Salário Líquido
"""
a = int(input("Lendo um número: "))
print("imprimindo o numero", a)
horas = int(input("Quanto você ganha por hora? "))
mes = int(input("Quantas horas trabalhas no mês? "))
  previa = int(horas*mes)
  leao =  previa*0.11
  inss =  previa*0.08
  sindicato = previa*0.05
print("Seu salário líquido é:", previa,"\nIR(11%): ", leao,"\nINSS(8%): ",inss,"\nSindicato(5%): ",sindicato)

"""
Exercicio 2 - Condicional

Faça um programa que lê as duas notas parciais obtidas por um aluno numa disciplina ao longo de um semestre, e calcule a sua média. A atribuição de conceitos obedece à tabela abaixo:

Média de Aproveitamento

A - Entre 9.0 e 10.0
B - Entre 7.5 e 9.0
C - Entre 6.0 e 7.5
D - Entre 4.0 e 6.0
E - Entre 4.0 e zero
"""
x = int(input("Please enter an integer: "))
y = int(input("Please other integer: "))
if x < 0 and y > 0:
     x = 0
     print('Negative changed to zero')
elif x == 0 or y == 0:
     print('Zero')
elif x == 1:
     print('Single')
else:
     print('More')
notaUm = int(input("Qual a nota parcial? "))
notaDois = int(input("E a segunda nota parcial? "))
media = (notaUm+notaDois)/2
if media >= 9.0:
  print("Sua nota é A e possui uma media de ", media,".")
elif media >= 7.5 and media < 9.0:
  print("Sua nota é B e possui uma media de ", media,".")  
elif media >= 6.0 and media < 7.5:
  print("Sua nota é C e possui uma media de ", media,".")  
elif media >= 4.0 and media < 6.0:
  print("Sua nota é D e possui uma media de ", media,".")  
elif media >= 0 and media < 4.0:
  print("Sua nota é E e possui uma media de ", media,".")  
"""
Exercicio 3 - For

Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo: Tabuada de 5:

"5 X 1 = 5"
"5 X 2 = 10"
"..."
"5 X 10 = 50"
"""
for i in range(5):
  print(i)
for i in range(0, 10, 3)
  print(i)
numero = int(input("Qual número deseja ver a tabuada? "))
for i in range(1,11):
  print(numero,"*",i,"=",numero*i)
"""
Exercicio 4 - While

Faça uma rotina que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.
"""
user = (input("Qual será o seu nome de usuário? "))
print("O usuário é ",user)
password = (input("Qual será a senha utilizada?"))
print("Para finalizar, realize o login.")
entrada = 0
while (entrada != user):
  entrada = (input("Digite o nome de usuário:"))
while (entrada != password):
  entrada = (input("Digite a senha:"))
print("Login realizado com sucesso.")
"""
Exercicio 5 - Listas

Faça uma rotina que leia um vetor de 10 números reais e mostre-os na ordem inversa.
"""
lista = []
for i in range(10):
  lista.append(input('Numero '+ str(i+1) + ':\n'))
lista.reverse()
print(lista)
"""
Exercicio 6 - Listas

Faça uma rotina que leia os dados de um cliente até que o usuário digite "fim" e os imprima na tela.
"""
cliente = []
while (entrada != "fim"):
  entrada = (input("Digite os dados:"))
  cliente.append(entrada)
print(cliente)
"""
Exercicio 7 - Funções

Faça um programa com uma função chamada somaImposto. A função possui dois parâmetros de entrada: taxaImpostoVendas, que é a quantia de imposto sobre vendas expressa em porcentagem e custo, que é o custo de um item antes do imposto. A função retorna o valor de custo incluindo o imposto sobre vendas.
"""
def somaImposto(taxaImpostoVendas, custo):
  total = ((taxaImpostoVendas/100)*custo)+custo
  return total

taxaImpostoVendas = int(input("Digite a quantia de imposto sobre vendas em porcentagem:"))
custo = int(input("Digite o custo do item: "))
print("o valor total do item é",somaImposto(taxaImpostoVendas,custo))